# version : "3.5"
# Docker Compose howa fichier kaygol l Docker :

# Ch7al mn container khasni ncrei ?
# Chno image aw Dockerfile dyal kol wa7ed ?
# Kifach yconnectiw m3a ba3d ?
# Chno volumes ?
# Chno variables d'environnement ?
# Chkon ybda lwel ?

volumes:
  wordpress:
    name: wordpress
    driver: local #
    driver_opts:
      type: none #utiliser un dossier
      device: /home/nel-khad/data/wordpress
      o: bind #bind ce path avec ce volume

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/nel-khad/data/mariadb
      o: bind


services :
  #le conteneur doit etre nome par mariadb car dans wordpress contient --dbhost=mariadb mais je sais pas ce qu'il fait avec cet info
  mariadb:
    build :
      context : ./requirements/mariadb #path a dockerfile de mariadb , docker va creer une image depuis dockerfile
    env_file :
      - .env #prendre les variable d'env depuis ce fichier
    volumes :
      - mariadb:/var/lib/mysql #ou est ce fichier et pourquoi il ne se suprime pas si je restarter le docker
    networks:
      - inception
    restart : always
    

  wordpress:
    build :
      context: ./requirements/wordpress #build an image from dockerfile in this dir
    env_file :
      - .env
    volumes :
      - wordpress:/var/www/html
    depends_on :
      - mariadb  
    networks:
      - inception
    restart : always

  nginx:
    build :
      context: ./requirements/nginx
    env_file :
      - .env
    ports:
      - "443:443" #conextion pc : container mais est ce que le pc represente browser /
    volumes :
      - wordpress:/var/www/html #3lach drnah ? 3lach bhalo bhal wordpress et 3lach nhtoh f had l path non pas un autre
    depends_on :
      - wordpress #3lach ?
    networks:
      - inception
    restart : always

networks:
    inception: #3lach network 3la bra 
    


#   docker compose up
#         |
#         v
# Build MariaDB
#         |
# Build WordPress
#         |
# Build Nginx
#         |
# Create network
#         |
# Create volumes
#         |
# Start MariaDB
#         |
# Start WordPress
#         |
# Start Nginx
#         |
# Browser --> HTTPS --> Nginx --> PHP-FPM --> MariaDB